lirantal/lockfile-lint

packages/lockfile-lint-api/__tests__/validators.host.test.js, packages/lockfile-lint-api/__tests__/validators.https.test.js, packages/lockfile-lint-api/__tests__/validators.scheme.test.js, packages/lockfile-lint-api/src/common/PackageError.js, packages/lockfile-lint-api/src/validators/ValidateHost.js, packages/lockfile-lint-api/src/validators/ValidateHttps.js, packages/lockfile-lint-api/src/validators/ValidateScheme.js, packages/lockfile-lint/bin/lockfile-lint.js
Provide more verbose information - which includes the package name - on errors encountered during validation. In order to solve this I created a custom error type called `PackageError` which prints out the package name as well as the original error message and stacktrace. It is used in validators.
#9 
More informative error message.
Added a test-case for each validator. Based on mocked packages containing a bad url these test cases assert that `PackageError` was thrown.
Example output:
```
$ lockfile-lint -p bad-yarn.lock --allowed-hosts yarn --validate-https -t yarn
ABORTING lockfile lint process due to error exceptions 
Encountered error Invalid URL: /registry.yarnpkg.com/debug/-/debug-4.1.1.tgz#3b72260255109c6b589cee050f1d516139664791 in package: "debug@^4.1.1" 
TypeError …
```
=> #9 More verbose error messages: include package name 

packages/lockfile-lint-api/README.md
Fixing typo in README.md
https://github.com/lirantal/lockfile-lint/issues/18
It makes the README.md example work without any additional debugging effort.
Manually tested the changes, since it is docs change, no need for unit tests.
=> docs: fixing typo in README.md example

packages/lockfile-lint-api/__tests__/validators.host.test.js, packages/lockfile-lint-api/__tests__/validators.https.test.js, packages/lockfile-lint-api/__tests__/validators.scheme.test.js, packages/lockfile-lint-api/src/validators/ValidateHost.js, packages/lockfile-lint-api/src/validators/ValidateHttps.js, packages/lockfile-lint-api/src/validators/ValidateScheme.js, packages/lockfile-lint/__tests__/cli.test.js, packages/lockfile-lint/bin/lockfile-lint.js
In ValidateScheme providing the actual scheme string against which we validate.
Added/Updated unit tests.
=> feat: provide the actual bad string in ValidateScheme

packages/lockfile-lint-api/__tests__/validators.host.test.js, packages/lockfile-lint-api/src/validators/ValidateHost.js
BREAKING CHANGE: lockfile-lint-api internal method API has changed its function
signature to allow receiving a value, and then an options object in a second
argument.
- [] Bug fix (non-breaking change which fixes an issue)
Relevant issues:
- #23
- #25
=> feat(emptyhostname): allow empty hostnames in api

packages/lockfile-lint-api/README.md
Fix the example code for `lockfile-lint-api`. As it currently is, it fails because the casing of `ParseLockfile` is incorrect in the example. Seems the docs weren't updated after the casing change occurred in the project.
Change casing from `ParseLockFile` to `ParseLockfile`
closes #37
=> docs: fix casing of ParseLockfile in example code for lockfile-lint-api

packages/lockfile-lint-api/__tests__/validators.host.test.js, packages/lockfile-lint-api/__tests__/validators.https.test.js, packages/lockfile-lint-api/__tests__/validators.scheme.test.js, packages/lockfile-lint-api/src/validators/ValidateHost.js, packages/lockfile-lint-api/src/validators/ValidateHttps.js, packages/lockfile-lint-api/src/validators/ValidateScheme.js
Prevent URL-based validators (Host, Scheme or HTTPS) throwing errors when no `resolved` field exists for the package.
fix #42
`ValidateHost`, `ValidateHttps` and `ValidateScheme` are updated to skip validation for any packages which don't have a `resolved` field in the lock-file.
https://github.com/lirantal/lockfile-lint/issues/42
Some package entries have no `resolved` field, for example those installed from the local filesystem. For these packages, protocol, scheme and host validation should be skipped completely as there is no external source to check, but the validators are currently trying to parse a non-existent URL which results in a validation failure.
New tests added to the `validateHost`, `validateHttps` and `validateScheme` specs to reflect the expected behaviour; tests failed …
=> fix(validators): skip packages with no resolved field

packages/lockfile-lint-api/README.md
Adds a note to the Validators table making it clear that URL-based validation will succeed for
entries which lack a `resolved` field.
Adds a note to the Validators table making it clear that URL-based validation will succeed for
entries which lack a `resolved` field.
https://github.com/lirantal/lockfile-lint/issues/42
Issue has been fixed by https://github.com/lirantal/lockfile-lint/issues/43, but the change in behaviour warrants an update to the documentation.
N/A
^ one cute animal picture per week is probably sufficient!
=> docs(lockfile-lint-api): add note about validation for local packages

packages/lockfile-lint-api/README.md
https://github.com/lirantal/lockfile-lint/issues/45
:goat:
=> Remove outdated "only yarn is supported" note

packages/lockfile-lint/src/cli.js
Made the tests not fail if the user locale isn't the default one (en).
This issue occurred because yargs detects the locale to output things.
Disabled the locale detection when configuring yargs.
Fix #41
I wanted to play with this great package but the tests didn't pass.
I cloned the project, installed the packages' dependencies and launched the tests. They failed.
I did the fix and checked the tests passed.
=> fix(lockfile-lint): fixed failing tests depending on user locale

packages/lockfile-lint-api/__tests__/parseNpmLockfile.test.js, packages/lockfile-lint-api/__tests__/validators.host.test.js, packages/lockfile-lint-api/__tests__/validators.https.test.js, packages/lockfile-lint-api/__tests__/validators.scheme.test.js, packages/lockfile-lint-api/package.json, packages/lockfile-lint-api/src/ParseLockfile.js, packages/lockfile-lint-api/src/validators/ValidateHost.js, packages/lockfile-lint-api/src/validators/ValidateHttps.js, packages/lockfile-lint-api/src/validators/ValidateScheme.js, packages/lockfile-lint/__tests__/main.test.js, yarn.lock
Will not override in the object if there is a matching dep and version
and will lint all the dependencies of dependencies.
Fixes #49
https://github.com/lirantal/lockfile-lint/issues/49
It solved the issue where if multiple dependencies had the same subdependencies (name and version) only one was added to the object. This was an issue if the first one was corrupt but the last one was fine, it would not be caught.
* Manually tested locally
* All unit tests are passing
=> fix(api): lint all dependencies in package-lock

packages/lockfile-lint-api/src/validators/ValidateHttps.js, packages/lockfile-lint-api/src/validators/ValidateScheme.js
a regression introduced via PR #53 due to flat package list
now being all-inclusive of packages, some of which have no
protocol or URL to resolve to (the nested deps) and so the
validators failed.
Fixes #58 
Missing from this PR is a set of unit tests to cover the error and will need to follow-up on.
=> fix(validators): only validating when URL is present

packages/lockfile-lint-api/src/validators/ValidateHost.js
Hosts validators were showing regression too incase the URL was an invalid one.
Comment in https://github.com/lirantal/lockfile-lint/issues/60#issuecomment-581812330
=> fix(validators): host validator enforced with URLs only

packages/lockfile-lint/__tests__/cli.test.js, packages/lockfile-lint/src/cli.js
When incompatible CLI arguments are provided they shouldn't just be ignored and lead to failure but rather a proper message should be provided to users.
Detecting the conflicting use of both `--allowed-schemes` and `--validate-https` and error'ing out with specifying that only one of those should be used.
Fixes #63 
Provides a better CLI experience for users.
Added a CLI test.
=> fix(cli): conflicting arguments will error

packages/lockfile-lint-api/package.json, packages/lockfile-lint/package.json
Many shells don't support single quotes including Windows cmd
=> fix(build): double quote globs in npm scripts

packages/lockfile-lint-api/src/validators/ValidateHost.js, packages/lockfile-lint-api/src/validators/ValidateScheme.js, packages/lockfile-lint/__tests__/cli.test.js
- switch to `string.includes` 
- improve usage of jest assertions
---
@lirantal I can't test this being I'm on Windows and tests just fail for master too. :/
=> chore: switch to `string.includes`

packages/lockfile-lint/__tests__/cli.test.js, packages/lockfile-lint/__tests__/main.test.js
It doesn't fix the Windows issue but makes sense to me :)
=> fix(tests): use `path.join` when concatenating paths

packages/lockfile-lint/__tests__/cli.test.js, packages/lockfile-lint/src/cli.js
BREAKING CHANGE: CLI may show an error when arguments conflict
and the order of short and long options was reversed to be
more descriptive on CLI options errors.
#64
=> feat(cli): error on conflicting options

packages/lockfile-lint/README.md
=> docs: update README with --allowed-urls option

packages/lockfile-lint-api/__tests__/validators.host.test.js, packages/lockfile-lint-api/__tests__/validators.url.test.js
Some tests in `validators.host.test.js` are testing that the `validate` method doesn't throw when they should be testing that validation succeeds and the resulting validation object doesn't contain any errors.
Address #77
Improve tests
=> fix(tests): update hosts validator tests

packages/lockfile-lint-api/__tests__/validators.host.test.js, packages/lockfile-lint-api/src/validators/ValidateHost.js
This PR fixes the problem where a host is provided with a port, such as `mydomain.com:1234` and treats it as-is if it can't parse it. 
Fixes #93
=> fix: support host:port syntax

packages/lockfile-lint/src/validators/index.js
Debugging for the CLI needed to enable specific DEBUG namespace to see each validator. Instead, put them all under the same "lockfile-lint" namespace so that it won't be hard to find the keys.
=> fix: all debug under lockfile-lint namespace

yarn.lock
Run `yarn install` to update `yarn.lock` and fix the CI publish fail.
Fixes the publish problem after issue #99.
This change is required to publish a newer version of the package.
`npm run lint` and `npm run test` passed in both sub-packages.
- N/A I have updated the documentation (if required).
- N/A I have added tests to cover my changes.
=> Update top-level yarn.lock to fix publish fail

packages/lockfile-lint-api/src/ParseLockfile.js
https://github.com/lirantal/lockfile-lint/issues/102 
Currently, it's calling https://github.com/lirantal/lockfile-lint/blob/d7564f8d20c9dbd4b8fc786f1d9967d7be6d6302/packages/lockfile-lint-api/src/ParseLockfile.js#L128   with 'undefined' (npmDepsTree) when there are no 'dependencies' in package-lock.json https://github.com/lirantal/lockfile-lint/blob/d7564f8d20c9dbd4b8fc786f1d9967d7be6d6302/packages/lockfile-lint-api/src/ParseLockfile.js#L116 and that causes Object.entries(npmDepsTree) to break.
Solution:
If not undefined call _flattenNpmDepsTree else set empty object
https://github.com/lirantal/lockfile-lint/issues/102
Locally
=> 102 fix empty dependencies

packages/lockfile-lint-api/package.json, packages/lockfile-lint-api/src/validators/ValidateHost.js, packages/lockfile-lint-api/src/validators/ValidateHttps.js, packages/lockfile-lint-api/src/validators/ValidatePackageNames.js, packages/lockfile-lint-api/src/validators/ValidateScheme.js, packages/lockfile-lint/package.json, packages/lockfile-lint/src/validators/index.js
Just getting rid of a dependency that, while barely used, pulls in a bunch of requirements. Here's an overview:
```
"lockfile-lint-api>debug": {
"builtin": {
"tty.isatty": true,
"util.deprecate": true,
"util.format": true,
"util.inspect": true
},
"globals": {
"console": true,
"document": true,
"localStorage": true,
"navigator": true,
"process": true
},
"packages": {
"lavamoat>@babel/highlight>chalk>supports-color": true,
"lockfile-lint-api>debug>ms": true
}
},
```
This is also contributing to the progress on #123 by getting rid of tty and process requirements
BREAKING:
bumped engine to v10 to remove all `const {URL} = require('url')`
I saw semantic-release is used, so this may need to be split into two conventional commits
=> fix #125 - remove debug dependency from lockfile-lint-api

README.md
Updating the README to include online mentions and references to implementations or discussions relating to the [2019's Lockfile Injection attack](https://snyk.io/blog/why-npm-lockfiles-can-be-a-security-blindspot-for-injecting-malicious-modules/).
=> docs: update for references of lockfile injection

packages/lockfile-lint-api/package.json, packages/lockfile-lint/package.json
defining `repository.path` in each `package.json` should inform tools like renovate to properly find the `CHANGELOG.md` files
fixes #141
without this information, tools like renovate look in the root of the repo and fail to find the details for the individual packages
=> fix(repository): defined `repository.path` property in `package.json`

packages/lockfile-lint/__tests__/cli.test.js, packages/lockfile-lint/bin/lockfile-lint.js
When adding a validator boolean flag to command line, the value was ignored, and the validator was activated even if its value was "false".
* Fixed some CLI tests failing on Windows with "Error: spawn UNKNOWN" due to running with `childProcess.spawn(cliExecPath, [...])`. Changed to `childProcess.spawn('node', [cliExecPath, ...])`
* Added validator only if commandValue is not falsy 
* Added tests to make sure validator does not run when flag is missing, or flag is set to "false"
* Added another cli test for the integrity validator
>**Note:** This does not resolve command-line with typos.
https://github.com/lirantal/lockfile-lint/issues/145
=> Fix #145: cli parsing - handle correctly false value for validator

packages/lockfile-lint-api/src/ParseLockfile.js, packages/lockfile-lint/__tests__/main.test.js
fix error handling for empty yarn lock files (#158)
Currently, running any validator against an empty lock file results in a exception with a stack trace, like this:
```
$ touch yarn.lock && npx lockfile-lint@4.10.1 --path yarn.lock --type yarn --allowed-hosts yarn npm yarn
ℹ ABORTING lockfile lint process due to error exceptions 
Unable to parse yarn lockfile "yarn.lock" 
TypeError: undefined is not iterable (cannot read property Symbol(Symbol.iterator))
at checkSampleContent (/home/candrews/.npm/_npx/456ed9a151c5043a/node_modules/lockfile-lint-api/src/ParseLockfile.js:24:36)
at yarnParseAndVerify (/home/candrews/.npm/_npx/456ed9a151c5043a/node_modules/lockfile-lint-api/src/ParseLockfile.js:41:49)
at ParseLockfile.parseYarnLockfile …
```
=> fix: error handling for empty yarn lock files (#158)

packages/lockfile-lint/bin/lockfile-lint.js
Prior to this fix, an error stack trace would be printed due to a bug in lockfile-lint's error handling.
It happened due to the `error()` function shadowing the local `error` variable in a try/catch scope.
This PR fixes that undefined error.
=> fix: error variable was shadowed by function

.changeset/weak-grapes-drum.md, package.json, packages/lockfile-lint/__tests__/cli.test.js, packages/lockfile-lint/__tests__/config.test.js, packages/lockfile-lint/src/config.js
Fixes #115 by providing referencing the long-form alias path of a CLI flag if it has errors associated with it, rather than the short-form single letter flag.
=> fix: better error messages that use the long-form alias of CLI flags

packages/lockfile-lint-api/__tests__/validators.packageNames.test.js, packages/lockfile-lint-api/src/validators/ValidatePackageNames.js
Fix #112 - when packages are used from registries outside of the public ones (like artifactory and such) then they may include a different URL convention to locate the package name.
This PR fixes lockfile-lint showing an error because it is actually unable to match the package name to the URL. The fix is to skip these cases. 
In the future we may treat this different, such as by allowing to specify a flag like package-name-url-prefixes where you can write https://checkmarx.jfrog.io/artifactory/api/npm/team-npm/ so that we parse everything after that to compare the package name for a match
#112
=> fix: skip validating package names outside of public registries

packages/lockfile-lint-api/src/validators/ValidatePackageNames.js, packages/lockfile-lint/__tests__/cli.test.js, packages/lockfile-lint/__tests__/fixtures/package-lock-v3-package-name-aliases.json, packages/lockfile-lint/bin/lockfile-lint.js, packages/lockfile-lint/src/config.js, packages/lockfile-lint/src/validators/index.js
Fix #175 
Package name aliases such as depicted in #175 would cause the `--validate-package-names` flag to trigger an issue. This PR creates a new trusted policy allow-list to match package names with their alias as pairs.
=> feat: allowed package name aliases

packages/lockfile-lint/__tests__/cli.test.js
Semantic changes to standaridze on test case naming convention
=> test: standardize on test semantics

packages/lockfile-lint-api/__tests__/validators.integrityHashType.test.js, packages/lockfile-lint-api/src/validators/ValidateIntegrity.js
Update the matching logic for `--integrity-exclude` to check the excluded package name against the package identifier used internally. Update the corresponding test suite with more realistic mocking data. Add an extra test case to ensure package names aren't matched partially.
Followup to #188
n/a
- Unit testing
(as seen in the diff)
- End-to-end testing
(linked my clone of this project to the project mentioned in [#187](https://github.com/lirantal/lockfile-lint/issues/187) and checked that the configuration behaved as expected)
_docs don't apply; no new cute animal picture, sorry_
=> Correct `--integrity-exclude` package name matching logic

packages/lockfile-lint/README.md
Fix grammar in config file name. Fixes #192
=> Fix grammar in config file name. Fixes #192

packages/lockfile-lint/README.md
Fix the cosmiconfig docs
As noted in #192 `.lockfile-lint.js` is invalid. `.lockfile-lintrc.js` should be a valid Cosmiconfig with the default setup which you appear to be using.
#192 
Fixes invalid docs
=> Update README.md to fix cosmiconfig reference

packages/lockfile-lint/README.md
=> docs: add references section for further supportive material
