lirantal/lockfile-lint

packages/lockfile-lint/README.md

Fix broken README with accidental text

fix(readme): cleaned up accidental text in readme

---

.travis.yml

Travis CI on Node.js platforms
CI matrix update
https://github.com/lirantal/lockfile-lint/issues/4
Run tests on more platforms

build(node12): test on Node.js 12

---

packages/lockfile-lint-api/package.json
packages/lockfile-lint/package.json

Fixes #14 
lockfile-lint:
```
C:\Users\xmr\Desktop\lockfile-lint\packages\lockfile-lint>npm pack --dry
npm notice
npm notice package: lockfile-lint@2.1.2
npm notice === Tarball Contents ===
npm notice 11.0kB LICENSE
npm notice 1.4kB  src/cli.js
npm notice 1.6kB  src/validators/index.js
npm notice 1.4kB  bin/lockfile-lint.js
npm notice 1.5kB  src/main.js
npm notice 4.7kB  package.json
npm notice 3.9kB  CHANGELOG.md
npm notice 6.5kB  README.md
npm notice === Tarball Details ===
npm notice name:          lockfile-lint
npm notice version:       2.1.2
npm notice filename:      lockfile-lint-2.1.2.tgz
npm notice package size:  9.2 kB
npm notice unpacked size: 32.0 kB
npm notice shasum:        5d148316e0aba93aa94b2e44330e6f026f801501
npm notice integrity: …
```

package.json: make the files to include stricter.

---

packages/lockfile-lint-api/__tests__/validators.scheme.test.js

Increasing test coverage
Test coverage

test(scheme): coverage for conditional validation check

---

packages/lockfile-lint-api/README.md

`CONTIRBUTING` -> `CONTRIBUTING` in `lockfile-lint-api` contributing section
No issue, but the change is self-explanatory
Fixes a typo in `lockfile-lint-api` README
README change, no new tests needed

Fix typo in `lockfile-link-api` README

---

yarn.lock

Update lockfile with packages being updated.

chore(lockfile): package updates

---

.travis.yml

As a follow up to PR #50 this updates the CI to also run tests in a non-English locale system
Related #50 
Makes sure we catch the tests that fail if they are run on a system with a different locale, as happened in #41

chore(build): update tests to include other locales

---

.travis.yml

Deploy stage didn't work properly due to wrong provider set for Travis CI straegy.

chore(build): fix deploy stage

---

README.md

It may not be clear as to what is the scope of malicious package trust that this security linter helps with.
Fixes #36

docs(readme): add security disclaimer

---

packages/lockfile-lint/README.md

Document which lockfiles are supported
Fixes #5 (partially, no pnp support yet)

docs(readme): add list of supported lockfiles

---

packages/lockfile-lint/__tests__/cli.test.js
packages/lockfile-lint/src/cli.js

Reverts lirantal/lockfile-lint#64

Revert "fix(cli): conflicting arguments will error"

---

packages/lockfile-lint/__tests__/cli.test.js

Requires #70 and then I will rebase.
Fixes #69

Fix tests on Windows

---

README.md

* Add usage example for npm-shrinkwrap.json
* Add note about no output === success
None
Prevents users from hitting this error:
```
ABORTING lockfile lint process due to error exceptions 
Unable to find relevant lockfile parser for "npm-shrinkwrap.json", consider passing the --type option. 
Error
at new ParsingError (/home/drazisil/.npm/_npx/12990/lib/node_modules/lockfile-lint/node_modules/lockfile-lint-api/src/common/ParsingError.js:27:33)
at ParseLockfile.parseSync (/home/drazisil/.npm/_npx/12990/lib/node_modules/lockfile-lint/node_modules/lockfile-lint-api/src/ParseLockfile.js:53:13)
at ValidateHostManager (/home/drazisil/.npm/_npx/12990/lib/node_modules/lockfile-lint/src/validators/index.js:40:27)
at validators.forEach.validator …
```

Add npm-shrinkwrap.json usage

---

README.md

People want to copy "shrinkwrap", but copy "shrinkwarp" instead. Amusing, but not as fun for them :)
https://github.com/lirantal/lockfile-lint/issues/80
Just trying to help.
Haven't tested, I don't think it's needed.
¯\\\_(ツ)_/¯

fixing a shrinkwrap typo

---

packages/lockfile-lint-api/src/validators/ValidateUrl.js

@lirantal didn't test this so please confirm before merging 🙂

Use `includes()` instead of `indexOf()`

---

packages/lockfile-lint/bin/lockfile-lint.js

Adds validation success message.
Close #76
Informs the user that everything is good so the user is not left wondering if the validation actually ran successfully.
Manually

feat: add validation success console message

---

packages/lockfile-lint/README.md

Updates the example 3, the argument ` --validate-https` and ` --allowed-schemes` cannot be used together. 
Fix #89

fix(readme) update example 3 remove invalid argument

---

packages/lockfile-lint/bin/lockfile-lint.js

@lirantal there you go :) We could get fancy and check for Windows, but it's your call for another time.

Remove emoji from output

---

packages/lockfile-lint/__tests__/cli.test.js
packages/lockfile-lint/bin/lockfile-lint.js

- Use log symbols for easier to read output (#21)
Fixes #21 
- By using symbols in the output it's easier to discern success or failure at a glance. Windows is also supported.
- Updated unit tests

feat: Use symbols for easier to read output (#21)

---

packages/lockfile-lint/__tests__/main.test.js

Added a test case to ensure passing unknown validator function name is handled gracefully. 
I wanted to improve code coverage to 100% (from 99.6%)  <a href="https://codecov.io/gh/lirantal/lockfile-lint"><img src="https://badgen.net/codecov/c/github/lirantal/lockfile-lint" alt="codecov"/></a>

test: Handle unknown validator function name

---

.github/workflows/main.yml

Solves
```
lerna ERR! Author identity unknown
lerna ERR! 
lerna ERR! *** Please tell me who you are.
lerna ERR! 
lerna ERR! Run
lerna ERR! 
lerna ERR!   git config --global user.email "you@example.com"
lerna ERR!   git config --global user.name "Your Name"
```
It might fails, I have the suspicion the publish still might fails afterwards, bit this helps.

fix: missing git step on release with lerna

---

packages/lockfile-lint-api/src/ParseLockfile.js

This removes a leftover from #126.
On my project that has a lot of dependencies, the list is pretty long and obscures the terminal output.
Thanks!
I didn't add an issue for this simple change.
This unwanted output to the console obscures the result.
I ran `yarn test` and ran the code with changes [on my project](https://github.com/firefox-devtools/profiler/).
before:
after:
I didn't add tests because that didn't seem useful for this change. Please tell me if you'd like me to look at adding some.

fix(lockfile-lint-api): remove extra console.log in yarn.lock parsing

---

.github/workflows/main.yml

Codecov Action v1 is deprecated, hence updating to v3 of this GitHub Action

chore: update codecov action to v3 

---

packages/lockfile-lint-api/src/validators/ValidateHost.js

Ignoring the try/catch clause of debugging errors as this isn't relevant in this case since original value is anyway that of a host. So effectively, we're not actually testing for a valid host. Could be solved in a future PR but currently this is a minor thing.
Fixes #138

fix: too noisy error messages

---

packages/lockfile-lint/README.md

docs: fix typo

---

.github/workflows/main.yml

Updating Node.js runtime versions on CI

build: update Node.js runtime versions

---

.github/workflows/main.yml

Update GitHub Actions versions in workflow file

build: update actions versions

---

.github/workflows/ci.yml

chore: allow CI to install deps without a synced lockfile

---

package-lock.json
packages/lockfile-lint/bin/lockfile-lint.js
packages/lockfile-lint/package.json

Fix #156 - add support to accept glob matching classifiers to match and scan multiple files

feat: support glob matching for multiple files

---

package-lock.json
package.json
packages/lockfile-lint/package.json

fix: update deps
